# Google Cloud Build configuration
substitutions:
  _REGION: 'europe-west1'
  _REPO: 'homepage'
  _IMAGE: '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/homepage:latest'

steps:
  # Configure Docker auth for Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev -q

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'homepage'
      - '--image=${_IMAGE}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'

images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY

